# Generated by Django 6.1 on 2026-09-01 07:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('BEEKEEPER', 'Beekeeper'), ('ADMIN', 'Admin')], default='BEEKEEPER', max_length=16)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'apiaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('hive_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='traceability.apiary')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='HoneyBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('harvest_date', models.DateField()),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('floral_source', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('HARVESTED', 'Harvested'), ('PROCESSED', 'Processed'), ('QUALITY_CHECKED', 'Quality checked'), ('PACKAGED', 'Packaged')], default='HARVESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='traceability.apiary')),
                ('beekeeper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to=settings.AUTH_USER_MODEL)),
                ('hives', models.ManyToManyField(related_name='batches', to='traceability.hive')),
            ],
            options={
                'verbose_name_plural': 'honey batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('HARVESTED', 'Harvested'), ('PROCESSED', 'Processed'), ('QUALITY_CHECKED', 'Quality checked'), ('PACKAGED', 'Packaged')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('data_hash', models.CharField(max_length=66)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('chain_event_index', models.PositiveIntegerField(blank=True, null=True)),
                ('chain_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_events', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='traceability.honeybatch')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(max_length=50, unique=True)),
                ('unit_count', models.PositiveIntegerField(default=1)),
                ('qr_code_image', models.ImageField(upload_to='qr_codes/')),
                ('public_url', models.URLField()),
                ('packaged_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='traceability.honeybatch')),
                ('linked_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_event', to='traceability.batchevent')),
                ('packaged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('purity_notes', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed')], max_length=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='traceability.honeybatch')),
                ('linked_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_check', to='traceability.batchevent')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
